spring.application.name=Voice Bot Application 
spring.data.mongodb.host=${SPRING_DATA_MONGODB_HOST:localhost}
spring.data.mongodb.port=${SPRING_DATA_MONGODB_PORT:27017}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:voicebot}
vapi.api.key=${VAPI_API_KEY:bbe7fbcd-9a8d-46fe-9576-b54171986d2a}
vapi.api.url=${VAPI_API_URL:https://api.vapi.ai}
server.port=${PORT:8080}